research_task:
  description: >
    As researcher, you need to fill in the ResearchOutput instance with a list of five different trends about {topic}
  expected_output: >
    A pydantic instance based on the class ResearchOutput
    ResearchOuput instance is a list of instances of ResearchUnit class
    Each instance has 4 elements:
    1. finding contains the finding about {topic}
    2. title is the best title representing the finding
    3. content is an explication of the finding in minimum 20 lines
    4. sources is a list of the different sources. Each source has a title and an url
  output_file: test.json
  agent: researcher

write_file_task:
  description: >
    As writer, you will structure the report with the analysis made by the agent researcher.
    You create an instance of ExecutiveReport 
  expected_output: >
    you use the pydantic instance ResearchOutput to create the instance ExecutiveReport
    The ExecutiveReport has 3 elements:
    1.title defines an elegant title for {topic}
    2.generation_date gives the date of the report
    3.executive_summary give a summary of the different trends generated by the task research_task
  context: [research_task]
  output_file: report.json
  agent: writer

format_task:
  description: >
    Save the content in the file {topic}_{date}.md in markdown format 
  expected_output: >
    A file with the name {topic}_{date}.md generated in markdown format
  context: [research_task,write_file_task]
  output_file: "{topic}_{date}.md"
  agent: formater